# Generated by Django 5.2.17 on 2026-09-06 20:31

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('trusted_contributor', 'TrustedContributor'), ('faculty_moderator', 'FacultyModerator'), ('site_admin', 'SiteAdmin')], db_index=True, default='student', max_length=32),
        ),
        migrations.CreateModel(
            name='ContributorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_identifier', models.CharField(max_length=254)),
                ('requested_role', models.CharField(choices=[('trusted_contributor', 'TrustedContributor'), ('faculty_moderator', 'FacultyModerator'), ('site_admin', 'SiteAdmin')], default='trusted_contributor', max_length=32)),
                ('token', models.CharField(default=accounts.models.invitation_token, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('revoked', 'revoked'), ('expired', 'expired')], db_index=True, default='pending', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.faculty')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.program')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.university')),
            ],
            options={
                'verbose_name': 'دعوة مساهم',
                'verbose_name_plural': 'دعوات المساهمين',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('university__isnull', False), ('faculty__isnull', False), ('program__isnull', False), ('course__isnull', False), _connector='OR'), name='invitation_scope_has_boundary')],
            },
        ),
        migrations.CreateModel(
            name='ContributorScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.course')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.faculty')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.program')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نطاق مساهم',
                'verbose_name_plural': 'نطاقات المساهمين',
                'constraints': [models.CheckConstraint(condition=models.Q(('university__isnull', False), ('faculty__isnull', False), ('program__isnull', False), ('course__isnull', False), _connector='OR'), name='contributor_scope_has_boundary')],
            },
        ),
        migrations.CreateModel(
            name='ModeratorScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.course')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.faculty')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.program')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نطاق مشرف',
                'verbose_name_plural': 'نطاقات المشرفين',
                'constraints': [models.CheckConstraint(condition=models.Q(('university__isnull', False), ('faculty__isnull', False), ('program__isnull', False), ('course__isnull', False), _connector='OR'), name='moderator_scope_has_boundary')],
            },
        ),
    ]
