# Generated by Django 5.2.17 on 2026-09-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'سنة دراسية',
                'verbose_name_plural': 'السنوات الدراسية',
                'ordering': ['program__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(allow_unicode=True, max_length=180)),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
                'ordering': ['university__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True)),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'جامعة',
                'verbose_name_plural': 'الجامعات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'code'), name='unique_course_name_code')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(allow_unicode=True, max_length=180)),
                ('is_demo', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='catalog.faculty')),
            ],
            options={
                'verbose_name': 'برنامج',
                'verbose_name_plural': 'البرامج',
                'ordering': ['faculty__university__name', 'faculty__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('is_demo', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.course')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='catalog.academicyearlevel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='catalog.program')),
            ],
            options={
                'verbose_name': 'طرح مادة',
                'verbose_name_plural': 'طروحات المواد',
                'ordering': ['program__faculty__university__name', 'program__faculty__name', 'program__name', 'year_level__order', 'term__order', 'course__name'],
            },
        ),
        migrations.AddField(
            model_name='academicyearlevel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_levels', to='catalog.program'),
        ),
        migrations.CreateModel(
            name='StudyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('summary', 'ملخص'), ('lecture', 'محاضرة'), ('past_exam', 'أسئلة دورة'), ('solution', 'حل'), ('book', 'كتاب'), ('practical', 'عملي'), ('other', 'غير ذلك')], default='summary', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=20)),
                ('contributor_name', models.CharField(blank=True, max_length=120)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('is_demo', models.BooleanField(default=False)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_documents', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalog.courseoffering')),
            ],
            options={
                'verbose_name': 'ملف دراسي',
                'verbose_name_plural': 'الملفات الدراسية',
                'ordering': ['offering__course__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_demo', models.BooleanField(default=False)),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='catalog.academicyearlevel')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
                'ordering': ['year_level__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='catalog.term'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='catalog.university'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('faculty', 'slug'), name='unique_program_slug_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('faculty', 'name'), name='unique_program_name_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='academicyearlevel',
            constraint=models.UniqueConstraint(fields=('program', 'order'), name='unique_year_level_order_per_program'),
        ),
        migrations.AddConstraint(
            model_name='academicyearlevel',
            constraint=models.UniqueConstraint(fields=('program', 'name'), name='unique_year_level_name_per_program'),
        ),
        migrations.AddIndex(
            model_name='studydocument',
            index=models.Index(fields=['status', 'content_type'], name='catalog_stu_status_8b3d95_idx'),
        ),
        migrations.AddIndex(
            model_name='studydocument',
            index=models.Index(fields=['academic_year'], name='catalog_stu_academi_8798d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('year_level', 'order'), name='unique_term_order_per_year_level'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('year_level', 'name'), name='unique_term_name_per_year_level'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'program', 'year_level', 'term', 'academic_year'), name='unique_course_offering_per_context'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('university', 'slug'), name='unique_faculty_slug_per_university'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='unique_faculty_name_per_university'),
        ),
    ]
