# Generated by Django 5.2.17 on 2026-09-06 20:45

import catalog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studydocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='scan_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'بانتظار الفحص'), ('clean', 'سليم'), ('infected', 'مصاب'), ('failed', 'فشل الفحص')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='uploaded_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=catalog.models.study_document_upload_path),
        ),
        migrations.AlterField(
            model_name='studydocument',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('uploaded_pending_scan', 'مرفوع بانتظار الفحص'), ('pending', 'بانتظار المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AddIndex(
            model_name='studydocument',
            index=models.Index(fields=['status', 'scan_status'], name='catalog_stu_status_8d42a6_idx'),
        ),
    ]
