# Generated by Django 5.2.17 on 2026-09-06 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_studydocument_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studydocument',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_study_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studydocument',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('uploaded_pending_scan', 'مرفوع بانتظار الفحص'), ('pending_review', 'بانتظار المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='DocumentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('scientific_error', 'خطأ علمي'), ('broken_file', 'ملف لا يفتح'), ('copyright', 'حقوق نشر'), ('inappropriate', 'محتوى غير مناسب'), ('other', 'غير ذلك')], default='other', max_length=32)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('reviewing', 'قيد المراجعة'), ('resolved', 'محلول'), ('rejected', 'مرفوض')], db_index=True, default='open', max_length=20)),
                ('reporter_contact', models.CharField(blank=True, max_length=254)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='catalog.studydocument')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بلاغ ملف',
                'verbose_name_plural': 'بلاغات الملفات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('summary', 'ملخص'), ('lecture', 'محاضرة'), ('past_exam', 'أسئلة دورة'), ('solution', 'حل'), ('book', 'كتاب'), ('practical', 'عملي'), ('other', 'غير ذلك')], default='summary', max_length=30)),
                ('internal_file_name', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.studydocument')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_versions', to='catalog.courseoffering')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_document_versions', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نسخة ملف',
                'verbose_name_plural': 'نسخ الملفات',
                'ordering': ['document', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='studydocument',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_documents', to='catalog.documentversion'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version_number'),
        ),
    ]
