# Generated by Django 5.2.17 on 2026-09-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_studydocument_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
