# Generated by Django 5.2.17 on 2026-09-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_documentversion_page_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingMaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('summary', 'ملخص'), ('lecture', 'محاضرة'), ('past_exam', 'أسئلة دورة'), ('solution', 'حل'), ('book', 'كتاب'), ('practical', 'عملي'), ('other', 'غير ذلك')], max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('student_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المتابعة'), ('fulfilled', 'تمت تلبيته'), ('rejected', 'مرفوض'), ('duplicate', 'مكرر')], db_index=True, default='open', max_length=20)),
                ('supervisor_notes', models.TextField(blank=True)),
                ('fulfilled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_material_requests', to='catalog.studydocument')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='catalog.courseoffering')),
            ],
            options={
                'verbose_name': 'طلب ملف ناقص',
                'verbose_name_plural': 'طلبات الملفات الناقصة',
                'ordering': ['-created_at'],
                'permissions': [('manage_missing_material_requests', 'Can manage missing material requests within assigned scope')],
                'indexes': [models.Index(fields=['status', 'created_at'], name='catalog_mis_status_326052_idx')],
            },
        ),
    ]
