# Generated by Django 5.2.17 on 2026-09-13 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_missingmaterialrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='moderator_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_document_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='content_owner_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='content_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='license_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='permission_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='rights_basis',
            field=models.CharField(blank=True, choices=[('contributor_original', 'من إعداد المساهم'), ('owner_permission', 'بإذن صريح من صاحب المحتوى'), ('open_license', 'بترخيص يسمح بالنشر')], max_length=32),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='rights_contact',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='rights_declaration_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='rights_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='rights_declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='content_owner_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='content_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='license_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='permission_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='rights_basis',
            field=models.CharField(blank=True, choices=[('contributor_original', 'من إعداد المساهم'), ('owner_permission', 'بإذن صريح من صاحب المحتوى'), ('open_license', 'بترخيص يسمح بالنشر')], max_length=32),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='rights_contact',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='rights_declaration_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='rights_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='rights_declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights_declared_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='rights_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='rights_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights_reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='report_type',
            field=models.CharField(choices=[('scientific_error', 'خطأ علمي'), ('broken_file', 'ملف لا يفتح'), ('copyright', 'انتهاك حقوق النشر'), ('inappropriate', 'محتوى غير مناسب'), ('other', 'غير ذلك')], default='other', max_length=32),
        ),
    ]
