# Generated by Django 5.2.17 on 2026-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_documentreport_moderator_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='full_download_count',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
